# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:q-bio.* OR cat:eess.*'

# 検索キーワード
keywords:
        drunkenness: 4
        intoxication: 4
        alcohol: 4
        HRV: 3
        heart rate variability: 3

# 通知の閾値
score_threshold: 0
